# TODO: switch to redcarpet
# markdown: redcarpet

# Site wide configuration

title: Dominic's Site
locale: en_US
description: A Software Engineer from London.
logo: site-logo.png
search: true
url: http://dchambers.github.io
#url: http://0.0.0.0:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Dominic Chambers
  avatar: https://avatars3.githubusercontent.com/u/283294?v=2&s=460
  email: dominic.chambers@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: dchambers
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: dominic.chambers@gmail.com
    analytics: UA-55018454-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
